version: '3.4'

services:
  api:
    image: wvxbs/to-do-list-rest:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3001:3001
    volumes:
      - .:/app

  db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
